import type { CatalogItem } from '../src/api/catalog';
import type { FeedbackItem } from '../src/api/feedback';

export const MOCK_ITEMS: CatalogItem[] = [
  {
    name: 'hello-world',
    type: 'skill',
    category: 'examples',
    description: 'A minimal example skill for testing the catalog UI.',
    arguments: [],
    has_hero: false,
    has_thumbnail: false,
    screenshot_count: 0,
    example_count: 0,
    thumbnail_url: null,
    hero_url: null,
    screenshots: [],
    examples: [],
    content_markdown: '## Hello\n\nUse this skill for testing.\n\n```python\nprint("hi")\n```',
    resources: [
      {
        path: 'scripts/run.py',
        name: 'run.py',
        url: '/catalog/skill/hello-world/resource/scripts/run.py',
        mime_type: 'text/x-python',
      },
    ],
  },
  {
    name: 'code-review',
    type: 'skill',
    category: 'engineering',
    description: 'Review code changes for correctness, clarity, and maintainability.',
    arguments: [],
    has_hero: true,
    has_thumbnail: true,
    screenshot_count: 2,
    example_count: 0,
    thumbnail_url: null,
    hero_url: null,
    screenshots: [],
    examples: [],
  },
  {
    name: 'greet',
    type: 'prompt',
    category: 'examples',
    description: 'Greet someone by name using a template argument.',
    arguments: [{ name: 'name', required: true, description: 'Person to greet' }],
    has_hero: false,
    has_thumbnail: false,
    screenshot_count: 0,
    example_count: 0,
    thumbnail_url: null,
    hero_url: null,
    screenshots: [],
    examples: [],
  },
];

export const MOCK_SERVER = {
  name: 'Example MCP Server',
  website_url: 'https://github.com/agoda-com/dropmcp',
  icon_url: '/icon.svg',
};

export const MOCK_FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb-1',
    created_at: '2026-06-17 10:00',
    feedback_type: 'correction',
    feedback: 'I edited a test to make it pass instead of fixing the code.',
    better_instruction: 'Never modify existing passing tests to mask a regression.',
    suggested_skill: null,
    model: 'claude-opus-4',
    client: 'cursor',
    skill_name: 'preserve-existing-tests',
    repo: 'dropmcp',
    details: null,
    status: 'new',
    resolution_url: null,
  },
  {
    id: 'fb-2',
    created_at: '2026-06-16 14:30',
    feedback_type: 'agent_work',
    feedback: 'After invoking a UI skill, I had to create a reusable snapshot helper.',
    better_instruction: 'When UI snapshots need stable fixtures, include a reusable snapshot helper script.',
    suggested_skill: 'ui-snapshot-helper',
    model: 'gpt-5',
    client: 'vscode',
    skill_name: 'web-design-guidelines',
    repo: 'dropmcp',
    details: {
      work_type: 'script_created',
      summary: 'Created a helper that stabilizes mocked feedback fixtures before snapshots.',
      artifacts: [
        {
          kind: 'script',
          action: 'created',
          path: 'scripts/stabilize_feedback_snapshots.ts',
          language: 'typescript',
          content: 'export function stableFeedback(items) {\n  return items.map((item) => ({ ...item, created_at: "fixed" }));\n}\n',
        },
      ],
    },
    status: 'triaged',
    resolution_url: 'https://gitlab.example.com/dropmcp/-/merge_requests/42',
  },
  {
    id: 'fb-3',
    created_at: '2026-06-15 09:15',
    feedback_type: 'correction',
    feedback: 'I used a Date object in browser code.',
    better_instruction: 'Format dates to strings on the server before sending to the browser.',
    suggested_skill: null,
    model: 'claude-opus-4',
    client: null,
    skill_name: null,
    repo: null,
    details: null,
    status: 'actioned',
    resolution_url: null,
  },
];
